name: CI/CD Pipeline for Apache Kafka on Windows

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build & Deploy ApacheKafka
    runs-on: windows-latest  # Use Windows for the build process

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      - name: Build with Maven
        working-directory: ApacheKafka  # Ensure pom.xml is here
        run: mvn clean package -DskipTests=false

      - name: Verify JAR file exists
        run: ls -R ApacheKafka/target/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apachekafka-jar
          path: ApacheKafka/target/*.jar  # Upload JAR file

      - name: Run Unit Tests
        working-directory: ApacheKafka
        run: mvn test

  docker:
    name: Build & Push Docker Image
    needs: build-deploy
    runs-on: ubuntu-latest  # Use Ubuntu for Docker tasks

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: apachekafka-jar
          path: ApacheKafka/target  # Restore JAR to target folder

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./ApacheKafka
          file: ./ApacheKafka/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/apachekafka:latest
